### ISSUE TITLE
fidoconfig library doesn't support "include" keyword 

### ISSUE THREAD

**Issue by IrvinDitz** [askovpen/goated#5]
goated can't load areas when provided with fidoconfig file which contains "include" of areas list.
e.g.:
/etc/ftn/fconf.conf:
...
include	areas.conf
...

config.yml
...
fidoconfig: /etc/ftn/fconf.conf
...

**Comment by askovpen** [comment]
he look full path in include. i eill be add ability to support relative paths

**Comment by askovpen** [comment]
a4d87ad01cd8a225473f451b5a7de516031af867 fixed. please check

**Comment by IrvinDitz** [comment]
Please merge pull request #7 which fixes regex as well.
