### ISSUE TITLE
Hardcoded CP866 message encoding 

### ISSUE THREAD

**Issue by IrvinDitz** [askovpen/goated#9]
lib/msgapi/message.go:
`func (m *Message) Decode() {
  enc:="CP866"
  m.Body=utils.DecodeCharmap(m.Body,enc)
  m.From=utils.DecodeCharmap(m.From,enc)
  m.To=utils.DecodeCharmap(m.To,enc)
  m.Subject=utils.DecodeCharmap(m.Subject,enc)
}`

enc should be read from "CHRS:" kludge of the message.

**Comment by askovpen** [comment]
yes. in future.

**Comment by IrvinDitz** [comment]
Initial support added in Pull #11. Closing.

**Comment by IrvinDitz** [comment]
FTS-5003.001:
2. Character set identification line
------------------------------------

  The character encoding of a message is specified in the "CHRS"
  control line.

  The CHRS control line is formatted as follows:

  ^ACHRS: <identifier> <level>

  Where <identifier> is a character string of no more than eight (8)
  ASCII characters identifying the character set or character encoding
  scheme used, and level is a positive integer value describing what
  level of CHRS the  message is written in.

  For backwards compatibility, "CHARSET" may be treated as a synonym
  for "CHRS".

  Some implementations do not add the <level> field and some
  implementations erroneously present "UTF-8 2" instead of "UTF-8 4".
  Well mannered implementations should gracefully handle this situation
  when reading messages. The recommended way of doing this is to
  ignore the level parameter and only use the name of the identifier.
  In future the level parameter may become obsolete.

  Incoming messages without "CHRS" control lines should be considered
  as being written in pure ASCII, but may be treated as being written
  in some default character set or character encoding scheme. Such as
  IBM codepage 437, IBM codepage 866 or UTF-8. It is recommended that
  message readers offer the user the option of manually selecting a
  different character set or encoding scheme for these messages on a
  per-area, per-message or other basis.

**Comment by IrvinDitz** [comment]
FTS-5003.001:
  Level 1 is no longer "current practise". The level 1 character
  sets are included here for backward compatibility.


  ASCII       ISO 646-1 (US ASCII)
  DUTCH       ISO 646 Dutch
  FINNISH     ISO 646-10 (Swedish/Finnish)
  FRENCH      ISO 646 French
  CANADIAN    ISO 646 Canadian
  GERMAN      ISO 646 German
  ITALIAN     ISO 646 Italian
  NORWEIG     ISO 646 Norwegian
  PORTU       ISO 646 Portuguese
  SPANISH     ISO 646 Spanish
  SWEDISH     ISO 646-10 (Swedish/Finnish)
  SWISS       ISO 646 Swiss
  UK          ISO 646 UK
  ISO-10      ISO 646-10 (Deprecated alias)


  Level 2 character sets (eight-bit, ASCII based)

  CP437       IBM codepage 437 (DOS Latin US)
  CP850       IBM codepage 850 (DOS Latin 1)
  CP852       IBM codepage 852 (DOS Latin 2)
  CP866       IBM codepage 866 (Cyrillic Russian)
  CP848       IBM codepage 848 (Cyrillic Ukrainian)
  CP1250      Windows, Eastern Europe
  CP1251      Windows, Cyrillic
  CP1252      Windows, Western Europe
  CP10000     Macintosh Roman character set

  LATIN-1     ISO 8859-1 (Western European)
  LATIN-2     ISO 8859-2 (Eastern European)
  LATIN-5     ISO 8859-9 (Turkish)
  LATIN-9     ISO 8859-15 (Western Europe with EURO sign)

  Level 2 obsolete character set identifiers (see note)

  IBMPC       IBM PC character sets for European
  +7_FIDO     IBM codepage 866, use CP866 instead
  MAC         Macintosh character set, use CPxxxxx instead


  Level 4

  UTF-8      UTF-8 encoding for the Unicode character set
